{% set name = "PyWinCtl" %}
{% set version = "0.4.01" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Kalmat/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: cafbe7869526700542431025761adb172b78a4be580ddaec42140d677c8b9df9

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]
    - pywin32 >=302  # [win]
    - python-xlib >=0.21  # [linux]
    - pyobjc-core >=8.1  # [osx]
    - typing_extensions >=4.4.0
    - pywinbox >=0.7
    - pymonctl >=0.92
test:
  requires:
    - python {{ python_min }}
  commands:
    - "DISPLAY=localhost:1.0 XDG_SESSION_TYPE=x11 xvfb-run -a python -c 'import pywinctl'"  # [linux]
  imports:
    - pywinctl  # [not linux] pywinbox fails on import as no display is available

about:
  home: https://github.com/Kalmat/PyWinCtl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'Cross-Platform toolkit to get info on and control windows on screen'
  dev_url: https://github.com/Kalmat/PyWinCtl

extra:
  recipe-maintainers:
    - '0xbe7a'
